# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        arguments: ['@App\Service\JsonResponseService', '@LoggerService']
        tags: ['controller.service_arguments']

    #Entities#
    App\Entity\:
        resource: '../src/Entity'

    #Repositories#
    App\Repository\:
        resource: '../src/Repository'

    #Services#
    App\Service\JsonResponseService:
        arguments: ['@request_stack']

    #Logger#
    App\Util\Logger\CustomLineFormatter: ~
    LoggerService:
        class: Monolog\Logger
        arguments: ["app", ["@monolog.handler.filter_error", "@monolog.handler.filter_success"]]

    #Middlewares#
    App\Subscriber\RequestResponseLogSubscriber:
        arguments: ["@LoggerService", '@request_stack']
    App\Subscriber\ExceptionSubscriber:
        arguments: ["@LoggerService", '@request_stack', '@App\Service\JsonResponseService']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # User Token Authenticator
    App\Security\UserTokenAuthenticator:
        arguments:
            - '@LoggerService'
            - '@App\Service\JsonResponseService'
            - '@doctrine.orm.default_entity_manager'

    # Project Token Authenticator
    App\Security\ProjectTokenAuthenticator:
        arguments:
            - '@LoggerService'
            - '@App\Service\JsonResponseService'
            - '@doctrine.orm.default_entity_manager'
